highlighter: rouge
permalink: /:year/:month/:day/:slug:output_ext
timezone: America/New_York
include: [~weng]
exclude: [.git/]

plugins:
  - jekyll-diagrams

kramdown:
  syntax_highlighter: true
  syntax_highlighter_opts:
    default_lang: "ocaml"

liquid:
  error_mode: 'warn'

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      category: "english"
  -
    scope:
      path: "cn"
      type: "pages"
    values:
      head: "cccc"