highlighter: rouge
permalink: /:year/:month/:day/:slug:output_ext
timezone: America/New_York
include: [~weng]
exclude: [.git/]

kramdown:
  syntax_highlighter: true
  syntax_highlighter_opts:
    default_lang: "ocaml"

plugins:
  - jekyll-analytics

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: 168108339           # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

liquid:
  error_mode: 'warn'

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      category: "english"
  -
    scope:
      path: "cn"
      type: "pages"
    values:
      head: "cccc"